parameters:
  tf_state_rg: ""
  tf_state_stor: ""
  tf_state_container: ""
  tf_environment: ""
  client_id: ""
  client_secret: ""
  tenant_id: ""
  subscription_id: ""

steps:
- bash: |
    terraform apply \
      -input=false \
      tfplan
  env:
    TF_STATE_RESOURCE_GROUP:  ${{ parameters.tf_state_rg }}
    TF_STATE_STORAGE_ACCT:    ${{ parameters.tf_state_stor }}
    TF_STATE_CONTAINER_NAME:  ${{ parameters.tf_state_container }}
    TF_VAR_environment:       ${{ parameters.tf_environment }}
    TF_IN_AUTOMATION:         'true'
    ARM_CLIENT_ID:            ${{ parameters.client_id }}
    ARM_CLIENT_SECRET:        ${{ parameters.client_secret }}
    ARM_TENANT_ID:            ${{ parameters.tenant_id }}
    ARM_SUBSCRIPTION_ID:      ${{ parameters.subscription_id }}
  displayName: Terraform Apply